export enum songTypes {
    //FETCH SONG
    FETCH_SONG_REQUEST ="FETCH_SONG_REQUEST",
    FETCH_SONG_SUCCESS ="FETCH_SONG_SUCCESS",
    FETCH_SONG_FAILURE ="FETCH_SONG_FAILURE",
    //FETCH SONGS
    FETCH_SONGS_REQUEST ="FETCH_SONGS_REQUEST",
    FETCH_SONGS_SUCCESS ="FETCH_SONGS_SUCCESS",
    FETCH_SONGS_FAILURE ="FETCH_SONGS_FAILURE",
    //FETCH STATISTICS
    FETCH_SONGS_STATISTICS_REQUEST ="FETCH_SONGS_STATISTICS_REQUEST",
    FETCH_SONGS_STATISTICS_SUCCESS ="FETCH_SONGS_STATISTICS_SUCCESS",
    FETCH_SONGS_STATISTICS_FAILURE ="FETCH_SONGS_STATISTICS_FAILURE",
     //FETCH SONG ALBUM
     FETCH_SONGS_ALBUM_REQUEST ="FETCH_SONGS_ALBUM_REQUEST",
     FETCH_SONGS_ALBUM_SUCCESS ="FETCH_SONGS_ALBUM_SUCCESS",
     FETCH_SONGS_ALBUM_FAILURE ="FETCH_SONGS_ALBUM_FAILURE",
    //FETCH SONG ARTIST
    FETCH_SONGS_ARTIST_REQUEST ="FETCH_ARTIST_ALBUM_REQUEST",
    FETCH_SONGS_ARTIST_SUCCESS ="FETCH_ARTIST_ALBUM_SUCCESS",
    FETCH_SONGS_ARTIST_FAILURE ="FETCH_ARTIST_ALBUM_FAILURE",
    //FETCH SONG GENRE
    FETCH_SONGS_GENRE_REQUEST ="FETCH_GENRE_ALBUM_REQUEST",
    FETCH_SONGS_GENRE_SUCCESS ="FETCH_GENRE_ALBUM_SUCCESS",
    FETCH_SONGS_GENRE_FAILURE ="FETCH_GENRE_ALBUM_FAILURE",
    //POST SONG
    POST_SONG_REQUEST ="POST_SONG_REQUEST",
    POST_SONG_SUCCESS ="POST_SONG_SUCCESS",
    POST_SONG_FAILURE ="POST_SONG_FAILURE",
    //UPDATE SONG
    UPDATE_SONG_REQUEST ="UPDATE_SONG_REQUEST",
    UPDATE_SONG_SUCCESS ="UPDATE_SONG_SUCCESS",
    UPDATE_SONG_FAILURE ="UPDATE_SONG_FAILURE",

    //DELETE SONG
    DELETE_SONG_REQUEST ="DELETE_SONG_REQUEST",
    DELETE_SONG_SUCCESS ="DELETE_SONG_SUCCESS",
    DELETE_SONG_FAILURE ="DELETE_SONG_FAILURE",
}