export enum songTypes {
    //FETCH SONG
    FETCH_SONG_REQUEST ="FETCH_SONG_REQUEST",
    FETCH_SONG_SUCCESS ="FETCH_SONG_SUCCESS",
    FETCH_SONG_FAILURE ="FETCH_SONG_FAILURE",
    //FETCH SONGS
    FETCH_SONGS_REQUEST ="FETCH_SONGS_REQUEST",
    FETCH_SONGS_SUCCESS ="FETCH_SONGS_SUCCESS",
    FETCH_SONGS_FAILURE ="FETCH_SONGS_FAILURE",
    //FETCH STATISTICS
    FETCH_SONGS_STATISTICS_REQUEST ="FETCH_SONGS_STATISTICS_REQUEST",
    FETCH_SONGS_STATISTICS_SUCCESS ="FETCH_SONGS_STATISTICS_SUCCESS",
    FETCH_SONGS_STATISTICS_FAILURE ="FETCH_SONGS_STATISTICS_FAILURE",
    //POST SONG
    POST_SONG_REQUEST ="POST_SONG_REQUEST",
    POST_SONG_SUCCESS ="POST_SONG_SUCCESS",
    POST_SONG_FAILURE ="POST_SONG_FAILURE",
    //UPDATE SONG
    UPDATE_SONG_REQUEST ="UPDATE_SONG_REQUEST",
    UPDATE_SONG_SUCCESS ="UPDATE_SONG_SUCCESS",
    UPDATE_SONG_FAILURE ="UPDATE_SONG_FAILURE",

    //DELETE SONG
    DELETE_SONG_REQUEST ="DELETE_SONG_REQUEST",
    DELETE_SONG_SUCCESS ="DELETE_SONG_SUCCESS",
    DELETE_SONG_FAILURE ="DELETE_SONG_FAILURE",
}